import type { Metadata } from "next";
import { Lato, Roboto } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const lato = Lato({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-lato",
  display: "swap",
});

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const BUILDER_API_KEY = process.env.NEXT_PUBLIC_BUILDER_API_KEY;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${roboto.variable} antialiased`}
      >
        {children}
        {/* Builder.io Visual Editor Script */}
        <Script
          src="https://cdn.builder.io/js/webcomponents"
          strategy="afterInteractive"
        />
        <Script id="builder-init" strategy="afterInteractive">
          {`
            if (typeof Builder !== 'undefined') {
              Builder.init('${BUILDER_API_KEY}');
            }
          `}
        </Script>
      </body>
    </html>
  );
}
